MBEDTLS_SOURCES := \
  vendor/mbedtls-3.6.7/3rdparty/everest/library/everest.c \
  vendor/mbedtls-3.6.7/3rdparty/everest/library/x25519.c \
  vendor/mbedtls-3.6.7/3rdparty/everest/library/Hacl_Curve25519_joined.c \
  vendor/mbedtls-3.6.7/3rdparty/p256-m/p256-m_driver_entrypoints.c \
  vendor/mbedtls-3.6.7/3rdparty/p256-m/p256-m/p256-m.c \
  vendor/mbedtls-3.6.7/library/aes.c \
  vendor/mbedtls-3.6.7/library/aesni.c \
  vendor/mbedtls-3.6.7/library/aesce.c \
  vendor/mbedtls-3.6.7/library/aria.c \
  vendor/mbedtls-3.6.7/library/asn1parse.c \
  vendor/mbedtls-3.6.7/library/asn1write.c \
  vendor/mbedtls-3.6.7/library/base64.c \
  vendor/mbedtls-3.6.7/library/bignum.c \
  vendor/mbedtls-3.6.7/library/bignum_core.c \
  vendor/mbedtls-3.6.7/library/bignum_mod.c \
  vendor/mbedtls-3.6.7/library/bignum_mod_raw.c \
  vendor/mbedtls-3.6.7/library/block_cipher.c \
  vendor/mbedtls-3.6.7/library/camellia.c \
  vendor/mbedtls-3.6.7/library/ccm.c \
  vendor/mbedtls-3.6.7/library/chacha20.c \
  vendor/mbedtls-3.6.7/library/chachapoly.c \
  vendor/mbedtls-3.6.7/library/cipher.c \
  vendor/mbedtls-3.6.7/library/cipher_wrap.c \
  vendor/mbedtls-3.6.7/library/constant_time.c \
  vendor/mbedtls-3.6.7/library/cmac.c \
  vendor/mbedtls-3.6.7/library/ctr_drbg.c \
  vendor/mbedtls-3.6.7/library/des.c \
  vendor/mbedtls-3.6.7/library/dhm.c \
  vendor/mbedtls-3.6.7/library/ecdh.c \
  vendor/mbedtls-3.6.7/library/ecdsa.c \
  vendor/mbedtls-3.6.7/library/ecjpake.c \
  vendor/mbedtls-3.6.7/library/ecp.c \
  vendor/mbedtls-3.6.7/library/ecp_curves.c \
  vendor/mbedtls-3.6.7/library/entropy.c \
  vendor/mbedtls-3.6.7/library/entropy_poll.c \
  vendor/mbedtls-3.6.7/library/error.c \
  vendor/mbedtls-3.6.7/library/gcm.c \
  vendor/mbedtls-3.6.7/library/hkdf.c \
  vendor/mbedtls-3.6.7/library/hmac_drbg.c \
  vendor/mbedtls-3.6.7/library/lmots.c \
  vendor/mbedtls-3.6.7/library/lms.c \
  vendor/mbedtls-3.6.7/library/md.c \
  vendor/mbedtls-3.6.7/library/md5.c \
  vendor/mbedtls-3.6.7/library/memory_buffer_alloc.c \
  vendor/mbedtls-3.6.7/library/nist_kw.c \
  vendor/mbedtls-3.6.7/library/oid.c \
  vendor/mbedtls-3.6.7/library/padlock.c \
  vendor/mbedtls-3.6.7/library/pem.c \
  vendor/mbedtls-3.6.7/library/pk.c \
  vendor/mbedtls-3.6.7/library/pk_ecc.c \
  vendor/mbedtls-3.6.7/library/pk_wrap.c \
  vendor/mbedtls-3.6.7/library/pkcs12.c \
  vendor/mbedtls-3.6.7/library/pkcs5.c \
  vendor/mbedtls-3.6.7/library/pkparse.c \
  vendor/mbedtls-3.6.7/library/pkwrite.c \
  vendor/mbedtls-3.6.7/library/platform.c \
  vendor/mbedtls-3.6.7/library/platform_util.c \
  vendor/mbedtls-3.6.7/library/poly1305.c \
  vendor/mbedtls-3.6.7/library/psa_crypto.c \
  vendor/mbedtls-3.6.7/library/psa_crypto_aead.c \
  vendor/mbedtls-3.6.7/library/psa_crypto_cipher.c \
  vendor/mbedtls-3.6.7/library/psa_crypto_client.c \
  vendor/mbedtls-3.6.7/library/psa_crypto_driver_wrappers_no_static.c \
  vendor/mbedtls-3.6.7/library/psa_crypto_ecp.c \
  vendor/mbedtls-3.6.7/library/psa_crypto_ffdh.c \
  vendor/mbedtls-3.6.7/library/psa_crypto_hash.c \
  vendor/mbedtls-3.6.7/library/psa_crypto_mac.c \
  vendor/mbedtls-3.6.7/library/psa_crypto_pake.c \
  vendor/mbedtls-3.6.7/library/psa_crypto_rsa.c \
  vendor/mbedtls-3.6.7/library/psa_crypto_random.c \
  vendor/mbedtls-3.6.7/library/psa_crypto_se.c \
  vendor/mbedtls-3.6.7/library/psa_crypto_slot_management.c \
  vendor/mbedtls-3.6.7/library/psa_crypto_storage.c \
  vendor/mbedtls-3.6.7/library/psa_its_file.c \
  vendor/mbedtls-3.6.7/library/psa_util.c \
  vendor/mbedtls-3.6.7/library/ripemd160.c \
  vendor/mbedtls-3.6.7/library/rsa.c \
  vendor/mbedtls-3.6.7/library/rsa_alt_helpers.c \
  vendor/mbedtls-3.6.7/library/sha1.c \
  vendor/mbedtls-3.6.7/library/sha256.c \
  vendor/mbedtls-3.6.7/library/sha512.c \
  vendor/mbedtls-3.6.7/library/sha3.c \
  vendor/mbedtls-3.6.7/library/threading.c \
  vendor/mbedtls-3.6.7/library/timing.c \
  vendor/mbedtls-3.6.7/library/version.c \
  vendor/mbedtls-3.6.7/library/version_features.c \
  vendor/mbedtls-3.6.7/library/pkcs7.c \
  vendor/mbedtls-3.6.7/library/x509.c \
  vendor/mbedtls-3.6.7/library/x509_create.c \
  vendor/mbedtls-3.6.7/library/x509_crl.c \
  vendor/mbedtls-3.6.7/library/x509_crt.c \
  vendor/mbedtls-3.6.7/library/x509_csr.c \
  vendor/mbedtls-3.6.7/library/x509write.c \
  vendor/mbedtls-3.6.7/library/x509write_crt.c \
  vendor/mbedtls-3.6.7/library/x509write_csr.c \
  vendor/mbedtls-3.6.7/library/debug.c \
  vendor/mbedtls-3.6.7/library/mps_reader.c \
  vendor/mbedtls-3.6.7/library/mps_trace.c \
  vendor/mbedtls-3.6.7/library/net_sockets.c \
  vendor/mbedtls-3.6.7/library/ssl_cache.c \
  vendor/mbedtls-3.6.7/library/ssl_ciphersuites.c \
  vendor/mbedtls-3.6.7/library/ssl_client.c \
  vendor/mbedtls-3.6.7/library/ssl_cookie.c \
  vendor/mbedtls-3.6.7/library/ssl_debug_helpers_generated.c \
  vendor/mbedtls-3.6.7/library/ssl_msg.c \
  vendor/mbedtls-3.6.7/library/ssl_ticket.c \
  vendor/mbedtls-3.6.7/library/ssl_tls.c \
  vendor/mbedtls-3.6.7/library/ssl_tls12_client.c \
  vendor/mbedtls-3.6.7/library/ssl_tls12_server.c \
  vendor/mbedtls-3.6.7/library/ssl_tls13_keys.c \
  vendor/mbedtls-3.6.7/library/ssl_tls13_server.c \
  vendor/mbedtls-3.6.7/library/ssl_tls13_client.c \
  vendor/mbedtls-3.6.7/library/ssl_tls13_generic.c
