"""Convert the supplied SVG paths to Core Graphics for iOS 6."""
from pathlib import Path
import re
import xml.etree.ElementTree as ET
root = Path(__file__).resolve().parent.parent
icons = {'settings':'settingstabbar.svg', 'info':'info.svg', 'receive':'geticontabbar.svg', 'history':'history.svg'}
out = ['// Generated by scripts/build_icons.py from Assets/Icons/*.svg.', 'static BOOL LSSuppliedIcon(NSString *name, CGContextRef c) {']
for name, filename in icons.items():
    svg = ET.parse(root / 'Assets/Icons' / filename).getroot()
    x0,y0,w,h = map(float,svg.attrib['viewBox'].split())
    scale = 24/max(w,h)
    def point(x,y):
        return f'{(float(x)-x0)*scale+(24-w*scale)/2:.8f}, {(float(y)-y0)*scale+(24-h*scale)/2:.8f}'
    out.append(f'    if ([name isEqual:@"{name}"]) {{')
    out.append('        CGContextBeginPath(c);')
    for path in svg.findall('{http://www.w3.org/2000/svg}path'):
        tokens = re.findall(r'[A-Za-z]|[-+]?(?:\d*\.\d+|\d+\.?\d*)(?:[eE][-+]?\d+)?',path.attrib['d'])
        i=0;cmd=None;x=y=0
        while i<len(tokens):
            if tokens[i].isalpha():
                cmd=tokens[i];i+=1
                if cmd=='Z':out.append('        CGContextClosePath(c);');continue
            count={'M':2,'L':2,'H':1,'V':1,'C':6}[cmd]
            args=tokens[i:i+count];i+=count
            if cmd in ('M','L'):
                x,y=map(float,args)
                method='MoveToPoint' if cmd=='M' else 'AddLineToPoint'
                out.append(f'        CGContext{method}(c, {point(x,y)});')
                if cmd=='M':cmd='L'
            elif cmd=='H':
                x=float(args[0]);out.append(f'        CGContextAddLineToPoint(c, {point(x,y)});')
            elif cmd=='V':
                y=float(args[0]);out.append(f'        CGContextAddLineToPoint(c, {point(x,y)});')
            elif cmd=='C':
                out.append(f'        CGContextAddCurveToPoint(c, {point(*args[0:2])}, {point(*args[2:4])}, {point(*args[4:6])});');x,y=map(float,args[4:6])
    out += ['        CGContextFillPath(c);','        return YES;','    }']
out += ['    return NO;', '}','']
(root / 'LSSuppliedIcons.inc').write_text('\n'.join(out))
